/** Popisky vstupů pro šablonu dat – převzaté z formulářů jednotlivých modulů. */
export const SCRAPED_LABELS: Record<string, string> = {
  "aftercare.accreditation": "Akreditace kvality a bezpečí (+0,015)",
  "aftercare.bedsOd24": "Počet lůžek OD 00024",
  "aftercare.em": "Vyžádaná extramurální péče",
  "aftercare.geriatrician": "Geriatr 0,4 úv./120 lůžek (OD 00037, +0,04)",
  "aftercare.geriatristFte": "Úvazky geriatrů",
  "aftercare.kTransNlp": "K_TransNLP",
  "aftercare.msShareOver65": "Podíl dg. G35–G37 > 65 % (OD 00005/00037, +0,15)",
  "aftercare.palliativeDoctor": "Lékař paliativní medicíny 0,4 úv./120 lůžek (OD 00030, +0,04)",
  "aftercare.pointsOd00015": "Body OD 00015 (1,63 Kč)",
  "aftercare.pointsOd00017": "Body OD 00017 – NIP (1,59 Kč)",
  "aftercare.pointsOd00020": "Body OD 00020 – DIOP (1,57 Kč)",
  "aftercare.pointsOd00033": "Body OD 00033/00035 (1,37 Kč)",
  "aftercare.transformationPlan": "Schválený transformační plán (OD 00021, 00026)",
  "aftercare.u572Days": "Dny s kódem U57.2 (+20 Kč/den)",
  "aftercare.u572ShareOver50": "Podíl U57.2 > 50 % (OD 00024/00037, +0,03)",
  "amb.gaup2025": "GAUP_2025",
  "amb.gaup2027": "GAUP_2027",
  "amb.hpRefTotal": "HP_ref (celkem)",
  "amb.uhrAmb2025": "Úhr_amb_2025",
  "casePayment.cmDeti": "CM_děti (dětská onkologie v KOC)",
  "casePayment.cmH2027": "CM_2027 skupina H",
  "casePayment.cmPovinneJpl": "CM případů s povinným JPL",
  "casePayment.em": "EM_2027,BFGH",
  "casePayment.losMedian2025": "Medián ošetřovací doby 2025",
  "casePayment.losMedian2027": "Medián ošetřovací doby 2027",
  "common.casesAllInsurers2025": "Počet případů 2025 za všechny ZP",
  "common.cmAllInsurers2025": "CM_2025 za všechny ZP",
  "common.insurerDistrictShare": "Koeficient podílu pojištěnců ZP v okrese",
  "common.vaccinationMet": "Celostátní podmínka proočkovanosti splněna",
  "dialysis.patientsHomeHd": "Domácí hemodialýza",
  "dialysis.patientsPd": "Peritoneální dialýza (váha 1,5)",
  "dialysis.patientsReported": "Referovaní pacienti celkem",
  "dialysis.pcelk": "PP_CELK – pacienti do 80 let celkem",
  "dialysis.points": "Body (HB 1,18 + bonifikace)",
  "dialysis.pointsLow": "Body výkonů 18530, 18550 (HB 0,92)",
  "dialysis.signals.c76661": "76661 (3 000 Kč)",
  "dialysis.signals.c76662": "76662 (4 500 Kč)",
  "dialysis.signals.c76663": "76663 (7 000 Kč)",
  "dialysis.signals.c76664": "76664 (10 500 Kč)",
  "dialysis.signals.c76667": "76667 (20 000 Kč)",
  "dialysis.txo": "PP_TXO – ostatní transplantovaní",
  "dialysis.txp": "PP_TXP – preemptivně transplantovaní",
  "dialysis.upHo": "Unikátní pojištěnci 2027",
  "dialysis.wlo": "PP_WLO – ostatní na čekací listině",
  "dialysis.wlp": "PP_WLP – preemptivně na čekací listině",
  "dialysis.zumZulp": "ZUM + ZULP",
  "gp.bonusAccreditation": "Akreditace vzdělávacího programu (+1 Kč)",
  "gp.bonusEducation": "≥ 50 % lékařů s dokladem celoživotního vzdělávání (+1 Kč, HB +0,04)",
  "gp.bonusPrevention": "Preventivní prohlídky ≥ 30 % (40–80 let) / ≥ 40 % (6–19 let) (+2 Kč)",
  "gp.episodes18": "Epizody péče / kontakty 18+ (90 Kč)",
  "gp.hbExtendedHours": "Rozšířené ordinační hodiny (HB +0,06)",
  "gp.kpp": "KPP_okres",
  "gp.nurseEpisodesLong": "Epizody sestry ≥ 30 min (303 Kč)",
  "gp.nurseEpisodesShort": "Epizody sestry < 30 min (151 Kč)",
  "gp.nurseMonths": "Měsíce se sestrou S2/S3 ≥ 40 h týdně",
  "gp.pbOther": "Body – ostatní a neregistrovaní (1,19 Kč)",
  "gp.pbPrevention": "Body – preventivní prohlídky",
  "gp.pbSelected": "Body – vybrané výkony (1,30 Kč)",
  "gp.pocusCount": "Počet výkonů 01050",
  "gp.pocusMonths": "Měsíce s nasmlouvaným 01050 (POCUS)",
  "gp.regulation.drugsNational": "Léčiva a ZP – celostátní Ø / přepočtený poj.",
  "gp.regulation.drugsProvider": "Léčiva a ZP – poskytovatel",
  "gp.regulation.exempt": "Regulace se neuplatní (ZPP nepřekročen / nezbytná péče)",
  "gp.regulation.incontNational": "Inkontinence – celostátní Ø",
  "gp.regulation.incontProvider": "Inkontinence – poskytovatel",
  "gp.regulation.physioNational": "Fyzioterapie 902 – celostátní Ø",
  "gp.regulation.physioProvider": "Fyzioterapie 902 – poskytovatel",
  "gp.regulation.requestedNational": "Vyžádaná péče – celostátní Ø",
  "gp.regulation.requestedProvider": "Vyžádaná péče – poskytovatel",
  "gp.teamFte": "Úv_Σ – celkové úvazky lékařů",
  "gp.teamMonths": "Měsíce plnění podmínek",
  "gp.zumZulp": "ZUM + ZULP",
  "gyn.education": "≥ 50 % lékařů s dokladem vzdělávání (+9 Kč)",
  "gyn.episodes18": "Epizody péče 18+ (90 Kč)",
  "gyn.geneticShare": "Podíl geneticky testovaných",
  "gyn.hours": "Ordinační hodiny 30 h / 5 dnů nebo 24 h / 4 dny (+9 Kč)",
  "gyn.infertilityCount": "Vyšetření neplodnosti (848 Kč)",
  "gyn.iso": "ISO 9001 (+9 Kč)",
  "gyn.months": "Počet měsíců",
  "gyn.nonRegisteredPoints": "Body nepravidelné péče (HB 1,00)",
  "gyn.pregnantCount": "Počet těhotných pojištěnek ZP",
  "gyn.prevention45": "Prevence ≥ 45 % registrovaných do 70 let (+6 Kč)",
  "gyn.registeredWomen": "Registrované pojištěnky s nárokem",
  "gyn.team": "Týmová praxe 2,0 úv. L3, 50 h týdně (+6 Kč)",
  "gyn.teamMidwife": "Porodní asistentka ≥ 20 h týdně (+5 Kč)",
  "gyn.ultrasoundOk": "UZ přístroj po r. 2012 s kontrolou (jinak ×0,50)",
  "gyn.ultrasoundShare": "Podíl s konziliárním UZ (32410/32420/63415)",
  "gyn.upHo": "Unikátní pojištěnci 2027",
  "gyn.zumZulp": "ZUM + ZULP",
  "homecare.exemptKp": "KP k těmto pojištěncům",
  "homecare.exemptPoints": "Body – pojištěnci s výkonem 06349/06360 (mimo maximum)",
  "homecare.severeDgShare": "Podíl pojištěnců s dg. C00–C97, G09–G99, F00–F99, I60–I69… > 35 % (HB +0,05 u 925; KN +0,15)",
  "homecare.specialisedShare": "Podíl pojištěnců s výkony 06325–06334 ≥ 35 % (KN +0,03)",
  "homecare.telemetryShare": "Podíl výkonů 06135/06137 na 06313–06318 ≥ 10 % (HB +0,02 u 925; KN +0,03)",
  "hospitalReg.ambPerformanceBase": "Úhrada za ambulantní výkony bez ZUM/ZULP",
  "hospitalReg.gaup": "Globální unikátní pojištěnci 2027",
  "labs.gen.hbRef": "HB ref. období",
  "labs.gen.kpHo": "KP_ho",
  "labs.gen.kpRef": "KP_ref",
  "labs.gen.pbHo": "PB_ho",
  "labs.gen.pbRef": "PB_ref",
  "labs.gen.popHo": "POP 2027",
  "labs.gen.popRef": "UOP_ref",
  "labs.gen.uhrRef": "UHR_ref",
  "labs.lab.accredited": "Akreditace ČSN ISO 15189 / NASKL R3",
  "labs.lab.hbHo": "Hodnota bodu 2027",
  "labs.lab.hbRefWeighted": "Vážená HB ref. období Σ PB_i·HB_i / PB_ref",
  "labs.lab.kpHo": "ZUM + ZULP 2027",
  "labs.lab.newServices": "Nově nasmlouvané výkony",
  "labs.lab.pbHo": "PB_ho",
  "labs.lab.pbRef": "PB_ref",
  "labs.lab.popHo": "POP_icz 2027",
  "labs.lab.popRef": "POP_ref",
  "labs.lab.uhrRef": "UHR_ref",
  "labs.rdgHoursBonus": "Ordinační doba ≥ 35 h / 5 dnů (resp. 70 h u screeningu) – HB +0,02",
  "odb913.kpHo": "KP_ho",
  "odb913.patientMonthsHo": "Σ pacient-měsíců 2027",
  "odb913.patientMonthsRef": "Σ pacient-měsíců 2025",
  "odb913.pbHo": "PB_ho",
  "odb913.popHo": "Unikátní pojištěnci 2027",
  "odb913.popRef": "Unikátní pojištěnci 2025",
  "odb913.severeDgShare": "Podíl pojištěnců s dg. C00–C97, E10.3–E11.7, F, G09–G99, I60–I69 > 25 % (HB +0,02, KN 1,02)",
  "odb913.uhrRef": "Uhr_ref",
  "oneDay.em": "EM_JP – vyžádaná extramurální péče",
  "palliative.deductions": "Odečet souběžné péče",
  "palliative.pb80091": "Body za výkon 80091 (jednotkově)",
  "palliative.pointsDays": "Body za výkony 80090 + 80091",
  "palliative.pointsOther": "Body za 80088, 80089, 09527",
  "palliative.popAdults": "Unikátní dospělí pojištěnci",
  "palliative.popChildren": "Unikátní dětští pojištěnci",
  "palliative.psychologist": "Psycholog ≥ 0,1 úv. na 1,0 lékaře (+0,02)",
  "palliative.socialWorker": "Zdravotně-sociální pracovník ≥ 0,3 úv. (+0,02)",
  "physio.education": "≥ 50 % nositelů s dokladem vzdělávání (KN +0,02)",
  "physio.exemptKp": "KP k těmto pojištěncům",
  "physio.exemptPoints": "Body – pojištěnci s dg. C50, E83, F84, G20–G23, G35, G51–G83, P07…",
  "physio.highIndividualShare": "Podíl výkonů 21221/21415 > 14 % (KN +0,02)",
  "physio.lowBasicShare": "Podíl výkonů 21113/21115/21315 < 50 % (HB +0,01, KN +0,02)",
  "physio.neuroTraumaShare": "Podíl pojištěnců s dg. G10–G14, I60–I69, S42… > 5 % (HB +0,07, KN +0,10)",
  "pu.cases2025": "Počet případů 2025",
  "pu.cases2027": "Počet případů 2027",
  "pu.cm2025A": "CM_2025 skupina A",
  "pu.cm2025AtoD": "CM_2025 skupiny A až D",
  "pu.cm2025D": "CM_2025 skupina D",
  "pu.cm2027AD": "CM_2027 skupiny A+D",
  "pu.cm2027Transfer": "z toho CM případů ukončených překladem",
  "pu.em2025": "EM_2025",
  "pu.em2027": "EM_2027",
  "pu.transfers2025": "Překlady 2025 (PPR)",
  "pu.transfers2027": "Překlady 2027 (PPR)",
  "pu.uhrEu2025": "ÚHR_EU,2025",
  "pu.uhrIsu2025": "ÚHR_ISU,2025",
  "pu.uhrPu2025": "ÚHR_PU,2025",
  "separated.cmCmp": "CM_CMP,2027 (iktové případy)",
  "separated.cmPovinneJpl": "CM případů s povinným JPL",
  "separated.em": "EM_2027,CE",
  "separated.mrsMet": "Podmínka vykázání mRS splněna",
  "specialists.education": "≥ 50 % nositelů s dokladem vzdělávání (+0,03 / KN 0,02)",
  "specialists.hbBase": "Základní hodnota bodu",
  "specialists.hours": "Ordinační hodiny 30 h / 5 dnů (operační 24 h / 4 dny) (+0,02 / KN 0,02)",
  "specialists.hoursPerWeek": "Nasmlouvaná kapacita (hodin týdně)",
  "specialists.odb903": "Odb. 903 – podíl dg. F84, R47, Q35… > 10 % (KN 0,08)",
  "specialists.ordering": "Objednávkový systém s přednostním ošetřením (+0,01 / KN 0,01)",
  "under50.cmAD": "CM skupin A, D",
  "under50.cmH": "CM skupiny H (psychiatrie)",
  "under50.cmPovinneJpl": "CM případů s povinným JPL",
  "under50.em": "EM_pod50,2027",
  "urgent.centrumProvazeni": "Centrum provázení (2,0 úv. ZS pracovníka)",
  "urgent.count09564": "Počet výkonů 09564 (převzetí od ZZS)",
  "urgent.count51887": "Počet výkonů 51887",
  "urgent.count78890": "Počet výkonů 78890 (12 500 Kč)",
  "urgent.ernMember": "Poskytovatel je členem ERN",
  "urgent.k": "K – podíl pojištěnců ZP (okres/region)",
  "urgent.kRegion": "K_region (ERN, provázení)",
  "urgent.kpUrg": "KP_urg (korunové položky)",
  "urgent.lpsAdults": "LPS pro dospělé (2 mil. × K)",
  "urgent.lpsChildren": "LPS pro děti a dorost (2 mil. × K)",
  "urgent.oncoCentre": "Komplexní onkologické centrum",
  "urgent.outage": "Výpadek provozu > 72 h (krácení 50 %)",
  "urgent.pbKv": "PB_KV (klinická vyšetření v den UP)",
  "urgent.pbLps": "PB_LPS",
  "urgent.pbUrg": "PB_urg (06720–06729)",
  "urgent.provazeniChildren": "Ukončená provázení dětí < 19 let",
}
